---
before:
  hooks:
    - make tidy

builds:
  - main: ./cmd/bookmarks/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.GitCommit={{ .ShortCommit }}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "snapshot-{{ .Commit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
